baseURL = "https://antistatique.github.io/grand"
languageCode = "fr-ch"
title = "Grand"
theme = "grand"

[params]
  instagramLabel = "instagram"
  instagramURL = "https://instagram.com/legrand"
  mailLabel = "Mail"
  mailURL = "mailto:@@@"
  copyright = "© 2023 GRAND Prix Romand de la Création"
  privacyLabel = "Privacy"
  privacyURL = "privacy"
  madebyLabel = "Design exceptionnel par Baston et Antistatique"
  madebyURL = "madeby"
  
  
  

[markup]
  [markup.goldmark]
	  [markup.goldmark.renderer]
	    unsafe = true

[[menu.nav]]
  name = "Nuit des Publivores"
  weight = -100 
  identifier = "nuit-des-publivores"
  url = "/nuit-des-publivores"
[[menu.nav]]
  name = "Jury"
  weight = -90 
  identifier = "jury-2023"
  url = "/jury-2023"
[[menu.nav]]
  name = "Catégories"
  weight = -80 
  identifier = "les_categories"
  url = "/les_categories"
[[menu.nav]]
  name = "Billetterie & inscriptions"
  weight = -70 
  identifier = "billetterie_inscription"
  url = "/billetterie_inscription" 
[[menu.nav]]
  name = "Sponsors"
  weight = -70 
  identifier = "sponsors"
  url = "/sponsors"      