baseURL = "https://associationgrand.ch"
languageCode = "fr-ch"
title = "GRAND Prix Romand de la Création"
description = "LE GRAND REVIENT LES 24 & 25 MAI ! L’objectif du GRAND Prix Romand de la Création est de rassembler chaque année un maximum de travaux de création en communication afin de mettre en lumière les nombreux talents de notre région. Le concours met en avant la créativité et le savoir-faire « Made in Suisse romande » depuis plus de 14 ans."
theme = "grand"

[params]
  instagramLabel = "Instagram"
  instagramURL = "https://www.instagram.com/associationgrand/"
  mailLabel = "Mail"
  mailURL = "mailto:hello@associationgrand.ch"
  copyright = "© 2023 GRAND Prix Romand de la Création"
  privacyLabel = "Privacy"
  privacyURL = "privacy"
  madebyLabel = "Design exceptionnel par Baston et Antistatique"
  madebyURL = "madeby"
  

[markup]
  [markup.goldmark]
	  [markup.goldmark.renderer]
	    unsafe = true

[[menu.nav]]
  name = "Nuit des Publivores"
  weight = -100 
  identifier = "nuit-des-publivores"
  url = "/nuit-des-publivores"
[[menu.nav]]
  name = "Jury"
  weight = -90 
  identifier = "jury-2023"
  url = "/jury"
[[menu.nav]]
  name = "Catégories"
  weight = -80 
  identifier = "les_categories"
  url = "/les_categories"
[[menu.nav]]
  name = "Billetterie & inscriptions"
  weight = -70 
  identifier = "billetterie_inscription"
  url = "/billetterie_inscription" 
[[menu.nav]]
  name = "Sponsors"
  weight = -70 
  identifier = "sponsors"
  url = "/sponsors"      