name: Deploy

on:
  push:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set deployment environment variables based on Git branches
        id: deploy_target
        run: |
          if [[ $GITHUB_REF == 'refs/heads/dev' ]]; then
              echo "DEPLOY_TARGET=sites/staging.associationgrand.ch" >> $GITHUB_ENV
          fi
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
              echo "DEPLOY_TARGET=sites/associationgrand.ch" >> $GITHUB_ENV
          fi

      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest

      - name: Build
        run: hugo --minify

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v3
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_SSH_KEY }}
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no -o PubkeyAcceptedKeyTypes=ssh-rsa"
          SOURCE: "public/"
          REMOTE_HOST: "ig7dp.ftp.infomaniak.com"
          REMOTE_USER: "ig7dp_antistatique"
          TARGET: "${{ env.DEPLOY_TARGET }}"